/**
 * ExportModal.jsx — Selective export with dependency resolution
 *
 * Props:
 *   pack       {BuiltPack}    The full pack
 *   isOpen     {boolean}
 *   onClose    {function}
 *
 * Formats:
 *   .zip  — separate .txt file per generator (via JSZip CDN)
 *   .json — full pack descriptor with metadata
 *   clipboard multi-tab — copy each generator to clipboard in sequence
 */
import { useState, useEffect } from 'react';
import { resolveDependencies } from '../utils/dependencyResolver';

const JSZIP_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';

// Lazy-load JSZip from CDN
let _JSZip = null;
async function loadJSZip() {
  if (_JSZip) return _JSZip;
  if (window.JSZip) { _JSZip = window.JSZip; return _JSZip; }
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = JSZIP_CDN;
    s.onload = () => { _JSZip = window.JSZip; resolve(_JSZip); };
    s.onerror = reject;
    document.head.appendChild(s);
  });
}

export default function ExportModal({ pack, isOpen, onClose }) {
  const [selected, setSelected] = useState({});
  const [report, setReport] = useState(null);
  const [format, setFormat] = useState('zip');
  const [exporting, setExporting] = useState(false);
  const [clipIndex, setClipIndex] = useState(-1);
  const [copiedSlug, setCopiedSlug] = useState('');

  // Init: select all generators
  useEffect(() => {
    if (!isOpen || !pack) return;
    const init = {};
    pack.generators.forEach(g => { init[g.slug] = true; });
    setSelected(init);
    setReport(null);
    setClipIndex(-1);
  }, [isOpen, pack]);

  // Recalculate dependency report on selection change
  useEffect(() => {
    if (!pack) return;
    const slugs = Object.entries(selected)
      .filter(([, v]) => v)
      .map(([k]) => k);
    if (slugs.length === 0) { setReport(null); return; }
    const r = resolveDependencies(pack.generators, slugs);
    setReport(r);
  }, [selected, pack]);

  function toggleAll(val) {
    const next = {};
    pack.generators.forEach(g => { next[g.slug] = val; });
    setSelected(next);
  }

  function toggle(slug) {
    setSelected(prev => ({ ...prev, [slug]: !prev[slug] }));
  }

  function includeDep(missingSlug) {
    setSelected(prev => ({ ...prev, [missingSlug]: true }));
  }

  // ─── Export logic ───

  function getExportGenerators() {
    if (!report) return [];
    return pack.generators.filter(g => report.exportSlugs.includes(g.slug));
  }

  async function doExport() {
    const gens = getExportGenerators();
    if (gens.length === 0) return;

    setExporting(true);
    try {
      if (format === 'zip') await exportZip(gens);
      else if (format === 'json') exportJson(gens);
      else if (format === 'clipboard') startClipboardFlow(gens);
    } finally {
      setExporting(false);
    }
  }

  async function exportZip(gens) {
    const JSZip = await loadJSZip();
    const zip = new JSZip();
    const folder = zip.folder(pack.theme.replace(/\s+/g, '-').toLowerCase());

    gens.forEach(g => {
      folder.file(
        `${g.slug}.txt`,
        `// ${g.title}\n// Role: ${g.role}\n// Generated by Perchance AI Pack Builder\n\n${g.code}`
      );
    });

    // Pack descriptor
    folder.file('_pack.json', JSON.stringify({
      theme: pack.theme,
      description: pack.description,
      masterSlug: pack.masterSlug,
      generators: gens.map(g => ({
        slug: g.slug, title: g.title, role: g.role, imports: g.imports
      }))
    }, null, 2));

    const blob = await zip.generateAsync({ type: 'blob' });
    triggerDownload(blob, `${pack.theme.replace(/\s+/g, '-').toLowerCase()}-pack.zip`, 'application/zip');
  }

  function exportJson(gens) {
    const payload = JSON.stringify({
      id: pack.id,
      theme: pack.theme,
      description: pack.description,
      masterSlug: pack.masterSlug,
      builtAt: pack.builtAt,
      generators: gens.map(g => ({
        slug: g.slug,
        title: g.title,
        role: g.role,
        imports: g.imports,
        code: g.code
      }))
    }, null, 2);

    const blob = new Blob([payload], { type: 'application/json' });
    triggerDownload(blob, `${pack.theme.replace(/\s+/g, '-').toLowerCase()}-pack.json`, 'application/json');
  }

  function startClipboardFlow(gens) {
    setClipIndex(0);
    copyGen(gens, 0);
  }

  async function copyGen(gens, idx) {
    if (idx >= gens.length) { setClipIndex(-1); return; }
    const gen = gens[idx];
    try {
      await navigator.clipboard.writeText(gen.code);
      setCopiedSlug(gen.slug);
      setTimeout(() => setCopiedSlug(''), 1500);
    } catch { /* ignore */ }
    setClipIndex(idx);
  }

  function triggerDownload(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  if (!isOpen) return null;

  const exportGens = getExportGenerators();
  const selectedCount = Object.values(selected).filter(Boolean).length;

  return (
    <div style={styles.overlay} onClick={onClose}>
      <div style={styles.modal} onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div style={styles.header}>
          <span style={styles.title}>📦 Export Generators</span>
          <button style={styles.closeBtn} onClick={onClose} aria-label="Close">×</button>
        </div>

        {/* Generator checkboxes */}
        <div style={styles.section}>
          <div style={styles.sectionHeader}>
            <span style={styles.sectionLabel}>
              Select generators ({selectedCount}/{pack?.generators?.length})
            </span>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button style={styles.tinyBtn} onClick={() => toggleAll(true)}>All</button>
              <button style={styles.tinyBtn} onClick={() => toggleAll(false)}>None</button>
            </div>
          </div>
          <div style={styles.checkList}>
            {pack?.generators?.map(g => (
              <label key={g.slug} style={styles.checkRow}>
                <input
                  type="checkbox"
                  checked={!!selected[g.slug]}
                  onChange={() => toggle(g.slug)}
                  style={{ accentColor: 'var(--color-primary, #4f98a3)' }}
                />
                <span style={styles.checkLabel}>
                  {g.title}
                  {g.slug === pack?.masterSlug && (
                    <span style={styles.masterTag}>master</span>
                  )}
                </span>
                <span style={styles.checkSlug}>{g.slug}</span>
              </label>
            ))}
          </div>
        </div>

        {/* Dependency warnings */}
        {report?.warnings?.length > 0 && (
          <div style={styles.warnBox}>
            <p style={styles.warnTitle}>⚠️ Dependency warnings</p>
            {report.warnings.map((w, i) => (
              <div key={i} style={styles.warnRow}>
                <span style={styles.warnText}>
                  <code style={styles.warnCode}>{w.dependent}</code>
                  {' imports '}
                  <code style={styles.warnCode}>[^{w.missing}.{w.listName}]</code>
                  {report.resolved.includes(w.missing)
                    ? <span style={styles.autoResolved}> (auto-included)</span>
                    : <span style={styles.unresolved}> (not in pack)</span>
                  }
                </span>
                {!selected[w.missing] && report.resolved.includes(w.missing) && (
                  <button
                    style={styles.depBtn}
                    onClick={() => includeDep(w.missing)}
                  >
                    + Include
                  </button>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Format selector */}
        <div style={styles.section}>
          <span style={styles.sectionLabel}>Export format</span>
          <div style={styles.formatRow}>
            {[
              { id: 'zip', label: '🗂 .zip', desc: 'Separate .txt per generator' },
              { id: 'json', label: '📐 .json', desc: 'Full pack descriptor' },
              { id: 'clipboard', label: '📋 Clipboard', desc: 'Copy one by one' }
            ].map(f => (
              <button
                key={f.id}
                style={{
                  ...styles.formatBtn,
                  ...(format === f.id ? styles.formatBtnActive : {})
                }}
                onClick={() => setFormat(f.id)}
              >
                <span>{f.label}</span>
                <span style={styles.formatDesc}>{f.desc}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Clipboard multi-step flow */}
        {format === 'clipboard' && clipIndex >= 0 && (
          <div style={styles.clipFlow}>
            <p style={styles.clipTitle}>
              Step {clipIndex + 1} of {exportGens.length}: {exportGens[clipIndex]?.title}
            </p>
            <div style={styles.clipActions}>
              {copiedSlug === exportGens[clipIndex]?.slug && (
                <span style={styles.clipCopied}>✅ Copied!</span>
              )}
              <button
                style={styles.btn}
                onClick={() => copyGen(exportGens, clipIndex)}
              >
                📋 Copy this generator
              </button>
              {clipIndex < exportGens.length - 1 ? (
                <button
                  style={styles.btnSecondary}
                  onClick={() => { setClipIndex(clipIndex + 1); copyGen(exportGens, clipIndex + 1); }}
                >
                  Next →
                </button>
              ) : (
                <button style={styles.btnSecondary} onClick={() => setClipIndex(-1)}>
                  ✅ Done
                </button>
              )}
            </div>
          </div>
        )}

        {/* Footer */}
        <div style={styles.footer}>
          <span style={styles.footerInfo}>
            {exportGens.length} generator{exportGens.length !== 1 ? 's' : ''} will be exported
            {report?.resolved?.length > 0 && (
              <span style={{ color: 'var(--color-warning, #bb653b)' }}>
                {' '}(+{report.resolved.length} auto-included)
              </span>
            )}
          </span>
          <button
            style={{
              ...styles.btn,
              opacity: exportGens.length === 0 ? 0.4 : 1
            }}
            onClick={doExport}
            disabled={exporting || exportGens.length === 0}
          >
            {exporting ? 'Exporting…' : `Export ${exportGens.length} generator${exportGens.length !== 1 ? 's' : ''}`}
          </button>
        </div>
      </div>
    </div>
  );
}

const styles = {
  overlay: {
    position: 'fixed', inset: 0,
    background: 'rgba(0,0,0,0.6)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    zIndex: 1000
  },
  modal: {
    background: 'var(--color-surface, #1c1b19)',
    border: '1px solid var(--color-border, #393836)',
    borderRadius: '12px', padding: '24px',
    width: '540px', maxWidth: '95vw',
    maxHeight: '85vh', overflowY: 'auto',
    boxShadow: '0 12px 40px rgba(0,0,0,0.5)'
  },
  header: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: '20px'
  },
  title: {
    fontSize: '1.1rem', fontWeight: 600,
    color: 'var(--color-text, #cdccca)'
  },
  closeBtn: {
    background: 'none', border: 'none', fontSize: '1.4rem',
    cursor: 'pointer', color: 'var(--color-text-muted, #797876)', lineHeight: 1
  },
  section: { marginBottom: '20px' },
  sectionHeader: {
    display: 'flex', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: '10px'
  },
  sectionLabel: {
    fontSize: '0.82rem', fontWeight: 600,
    color: 'var(--color-text-muted, #797876)',
    textTransform: 'uppercase', letterSpacing: '0.04em'
  },
  tinyBtn: {
    padding: '3px 10px', fontSize: '0.75rem',
    background: 'var(--color-surface-dynamic, #2d2c2a)',
    color: 'var(--color-text-muted, #797876)',
    border: '1px solid var(--color-border, #393836)',
    borderRadius: '4px', cursor: 'pointer'
  },
  checkList: { display: 'flex', flexDirection: 'column', gap: '6px' },
  checkRow: {
    display: 'flex', alignItems: 'center', gap: '10px',
    padding: '8px 12px',
    background: 'var(--color-surface-offset, #1d1c1a)',
    borderRadius: '6px', cursor: 'pointer'
  },
  checkLabel: {
    flex: 1, fontSize: '0.9rem',
    color: 'var(--color-text, #cdccca)', display: 'flex', alignItems: 'center', gap: '6px'
  },
  masterTag: {
    padding: '1px 6px',
    background: 'var(--color-primary-highlight, #313b3b)',
    color: 'var(--color-primary, #4f98a3)',
    borderRadius: '3px', fontSize: '0.7rem', fontWeight: 700
  },
  checkSlug: {
    fontSize: '0.75rem', fontFamily: 'monospace',
    color: 'var(--color-text-faint, #5a5957)'
  },
  warnBox: {
    background: 'var(--color-warning-highlight, #564942)',
    border: '1px solid var(--color-warning, #bb653b)',
    borderRadius: '8px', padding: '12px 14px',
    marginBottom: '20px'
  },
  warnTitle: {
    fontSize: '0.85rem', fontWeight: 600,
    color: 'var(--color-warning, #bb653b)', margin: '0 0 8px'
  },
  warnRow: {
    display: 'flex', justifyContent: 'space-between',
    alignItems: 'center', gap: '8px', marginBottom: '6px'
  },
  warnText: { fontSize: '0.82rem', color: 'var(--color-text-muted, #797876)' },
  warnCode: {
    fontFamily: 'monospace', fontSize: '0.8rem',
    color: 'var(--color-text, #cdccca)'
  },
  autoResolved: { color: 'var(--color-success, #6daa45)', fontSize: '0.8rem' },
  unresolved: { color: 'var(--color-error, #dd6974)', fontSize: '0.8rem' },
  depBtn: {
    padding: '3px 10px', fontSize: '0.75rem',
    background: 'var(--color-surface-dynamic, #2d2c2a)',
    color: 'var(--color-primary, #4f98a3)',
    border: '1px solid var(--color-primary, #4f98a3)',
    borderRadius: '4px', cursor: 'pointer', whiteSpace: 'nowrap'
  },
  formatRow: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  formatBtn: {
    flex: 1, padding: '10px 14px',
    background: 'var(--color-surface-offset, #1d1c1a)',
    border: '1px solid var(--color-border, #393836)',
    borderRadius: '8px', cursor: 'pointer',
    display: 'flex', flexDirection: 'column',
    alignItems: 'flex-start', gap: '3px',
    fontSize: '0.88rem', fontWeight: 600,
    color: 'var(--color-text, #cdccca)',
    transition: 'border-color 0.15s'
  },
  formatBtnActive: {
    border: '1px solid var(--color-primary, #4f98a3)',
    background: 'var(--color-primary-highlight, #313b3b)'
  },
  formatDesc: {
    fontSize: '0.72rem', fontWeight: 400,
    color: 'var(--color-text-muted, #797876)'
  },
  clipFlow: {
    background: 'var(--color-surface-offset, #1d1c1a)',
    borderRadius: '8px', padding: '14px',
    marginBottom: '20px'
  },
  clipTitle: {
    fontSize: '0.9rem', color: 'var(--color-text, #cdccca)',
    margin: '0 0 10px'
  },
  clipActions: { display: 'flex', gap: '8px', alignItems: 'center' },
  clipCopied: { fontSize: '0.85rem', color: 'var(--color-success, #6daa45)' },
  footer: {
    display: 'flex', justifyContent: 'space-between',
    alignItems: 'center', gap: '16px',
    paddingTop: '16px',
    borderTop: '1px solid var(--color-divider, #262523)'
  },
  footerInfo: { fontSize: '0.82rem', color: 'var(--color-text-muted, #797876)' },
  btn: {
    padding: '10px 22px',
    background: 'var(--color-primary, #4f98a3)',
    color: '#fff', border: 'none', borderRadius: '8px',
    cursor: 'pointer', fontWeight: 600, fontSize: '0.9rem'
  },
  btnSecondary: {
    padding: '9px 18px',
    background: 'var(--color-surface-dynamic, #2d2c2a)',
    color: 'var(--color-text, #cdccca)',
    border: '1px solid var(--color-border, #393836)',
    borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem'
  }
};
